name: 'retail_dbt'
version: '1.0.0'
config-version: 2

profile: 'retail_dbt'

model-paths: ['models']

models:
  retail_dbt:
    staging:
      +materialized: view
    marts:
      +materialized: view
